config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'bzclass' && password == '12345'
  end
  mount Sidekiq::Web, at: "/sidekiq"
  mount Ckeditor::Engine => '/ckeditor'

  controller 'welcome' do
    get 'index'
    get 'news'
    get 'contacts'
    post 'feedback'
    get 'about'
    get 'news/:category_slug/:slug' => 'welcome#show',            as: :post
  end

  root 'welcome#index'



  scope 'lk', module: 'lk' do
    root to: redirect('/login'),   as: :lk
    resources     :users, except: [ :index, :destroy ]
    resources     :user_sessions
    resources     :password_resets
    resources     :payments
    resources     :payouts
    get 'news'                      => 'categories#index',      as: :lk_news
    get 'news/:slug'                => 'categories#show',       as: :lk_category
    get 'news/:category_slug/:slug' => 'posts#show',            as: :lk_post
  end

  namespace 'admin', path: 'adm' do
    root 'users#index'
    resources :users
    resources :questions
    resources :payouts, only: [ :index ]
    post 'payouts/:user_id/pay' => 'payouts#pay', as: :pay
    resources :settings
    resources :mailers
    resources :posts
    resources :categories
  end

  get 'login'     =>  'lk/user_sessions#new',     as: :login
  get 'logout'    =>  'lk/user_sessions#destroy', as: :logout
  get 'profile'   =>  'lk/users#show',            as: :profile
  get 'lk/faq'    => 'application#faq',           as: :faq
  get 'lk/grant'  => 'application#grant',         as: :grant
  post 'lk/grant' => 'application#grant_request', as: :grant_request
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy, counter_cache: true
  validates :name, presence: true
  # validates :is_public, presence: true
  include Sluggable

  scope :is_public, -> { where(is_public: true) }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  defaults resource_class: Category, collection_name: 'categories', instance_name: 'category'

  def create
    create! do |format|
      format.html { redirect_to admin_posts_path }
    end
  end

  def update
    update! do |format|
      format.html { redirect_to admin_posts_path }
    end
  end

  def destroy
    destroy! do |format|
      format.html { redirect_to admin_posts_path }
    end
  end

  protected

  def collection
    get_collection_ivar ||
      set_collection_ivar(end_of_association_chain.paginate page: params[:page])
  end

  def category_params
    params.require(:category).permit(:id, :name, :is_public)
  end
end

app/controllers/lk/categories_controller.rb
class Lk::CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @category = @categories.first
    @main_post = @category.posts.is_main.first
    @posts = @category.posts.not_main.paginate(page: params[:page], per_page: 3).order(id: :desc)
  end

  def show
    @categories = Category.all
    @category = Category.includes(:posts).find_by_slug(params[:slug])
    @main_post = @category.posts.is_main.first
    @posts = @category.posts.not_main.paginate(page: params[:page], per_page: 3).order(id: :desc)
  end

end

app/controllers/lk/password_resets_controller.rb
# app/controllers/password_resets_controller.rb
class Lk::PasswordResetsController < ApplicationController
  skip_before_action :require_login, :redirect_if_do_not_pay
  layout 'login'
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_reset_password_instructions!
      redirect_to(login_path, notice: 'Мы отправили вам email с инструкциями восстановления')
    else
      flash.now[:alert] = 'Email не найден'
      render :create
    end
  end

  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])
    if @user.blank?
      not_authenticated
      return
    end
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      redirect_to(login_path, notice: 'Вы успешно изменили пароль. Теперь Вы можете входить с систему.')
    else
      flash.now[:alert] = @user.errors.full_messages.join('; ')
      render action: "edit"
    end
  end
end

app/controllers/lk/payments_controller.rb
class Lk::PaymentsController < ApplicationController
  skip_before_action :redirect_if_do_not_pay

  def new
    redirect_to lk_news_path if current_user.is_active? && current_user.days_left > 10
    @payment = current_user.current_payment
  end

end

app/controllers/lk/payouts_controller.rb
class Lk::PayoutsController < ApplicationController
  def new
    @payout = current_user.payouts.new
    @payouts = current_user.payouts.includes(:refferal)
  end

  def create
    if current_user.account.is_waiting_for_payout?
      redirect_to new_payout_path, alert: 'Вы уже ожидаете вывода средств!'
    elsif params[:payout][:wallet].blank?
      redirect_to new_payout_path, alert: 'Укажите номер qiwi кошелька для вывода'
    else
      current_user.create_payouts(params[:payout][:wallet])
      redirect_to new_payout_path, notice: 'Ваш запрос в ближайшее время будет рассмотрен.'
    end
  end

end

app/controllers/lk/posts_controller.rb
class Lk::PostsController < ApplicationController

  def index
  end

  def show
    @category = Category.find_by_slug params[:category_slug]
    @post = @category.posts.find_by_slug params[:slug]
  end

end

app/controllers/lk/user_sessions_controller.rb
class Lk::UserSessionsController < ApplicationController

  skip_before_action :require_login, except: [:destroy]
  skip_before_action :redirect_if_do_not_pay
  layout 'login'

  def new
    redirect_to current_user_path if current_user
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember_me])
      redirect_to current_user_path(@user), notice: 'Успешный вход!'
    else
      flash.now[:alert] = 'Проблемы авторизации'
      render action: 'new'
    end
  end

  def destroy
    logout
    # redirect_to root_path, notice: 'Успешный выход!'
    redirect_to root_path
  end
end

app/controllers/lk/users_controller.rb
class Lk::UsersController < ApplicationController
  skip_before_action :require_login, :redirect_if_do_not_pay, only: [ :new, :create ]
  layout 'login', only: [ :new, :create ]
  before_action :redirect_to_profile, only: [ :new, :create ]
  def show

  end

  def new
    @user = User.new
    @user.parent_id = params[:id]

  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        login(params[:user][:email], params[:user][:password])
        format.html { redirect_to login_path, notice: 'Вы успешно зарегистрировались в системе' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if User.authenticate(current_user.email, params[:user][:current_password])
        update_params = user_params.slice(:password, :password_confirmation)
        if current_user.update(update_params)
          format.html { redirect_to profile_path, notice: 'Успешное редактирование' }
        else
          format.html { render :show }
        end
      else
        flash.now[:alert] = 'Текущий пароль некорректен'
        format.html { render :show }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :name,
        :phone,
        :email,
        :password,
        :password_confirmation,
        :parent_id,
        :acceptance_of_the_offer
      )
    end

    def redirect_to_profile
      redirect_to profile_path if current_user
    end
end

app/views/lk/categories/_post.html.slim
.page-news-block
  .page-news-block-img
    = image_tag post.image.url(:thumb)
  h4
    = link_to post.name, lk_post_path(post.category.slug, post.slug)
  span
    strong= post.category.name
    = post.created_at.localtime.strftime("%d.%m.%Y")
  p= post.short_description
  = link_to 'Подробнее...', lk_post_path(post.category.slug, post.slug)

app/views/lk/categories/index.html.slim
.content
  .container
    h1 Новости
    .news-cats
      - @categories.each do |category|
        = link_to category.name, lk_category_path(category.slug), class: "#{'active-cat' if category == @category}"
      / a.active-cat href="#"  Тренды
      / a href="#"  База знаний
      / a href="#"  Новости проекта
- if @main_post.present?
  .main-new.post
    .container style="width:1000px"
      - if @main_post.image.present?
        .post-thumb
          = image_tag @main_post.image.url(:_1000)
      .info-post
        .pre-info-post
          h3= @main_post.name
          p= @main_post.short_description
          = link_to 'Подробнее..', lk_post_path(@main_post.category.slug, @main_post.slug), class: 'permal'
        .main-new-date
          = link_to @main_post.category.name, lk_category_path(@main_post.category.slug)
          span=@main_post.created_at.localtime.strftime("%d.%m.%Y")
.page-news.clearfix
  .container
    = render partial: 'lk/categories/post', collection: @posts

  .centered
    = will_paginate @posts, renderer: BootstrapPagination::Rails
div style="width:100%;height:120px;float:left"

app/views/lk/categories/show.html.slim
.content
  .container
    h1 Новости
    .news-cats
      - @categories.each do |category|
        = link_to category.name, lk_category_path(category.slug), class: "#{'active-cat' if category == @category}"
      / a.active-cat href="#"  Тренды
      / a href="#"  База знаний
      / a href="#"  Новости проекта
- if @main_post.present?
  .main-new.post
    .container style="width:1000px"
      - if @main_post.image.present?
        .post-thumb
          = image_tag @main_post.image.url(:_1000)
      .info-post
        .pre-info-post
          h3= @main_post.name
          p= @main_post.short_description
          = link_to 'Подробнее..', lk_post_path(@main_post.category.slug, @main_post.slug), class: 'permal'
        .main-new-date
          = link_to @main_post.category.name, lk_category_path(@main_post.category.slug)
          span=@main_post.created_at.localtime.strftime("%d.%m.%Y")
.page-news.clearfix
  .container
    = render partial: 'lk/categories/post', collection: @posts

  .centered
    = will_paginate @posts, renderer: BootstrapPagination::Rails
div style="width:100%;height:120px;float:left"