config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'bzclass' && password == '12345'
  end
  mount Sidekiq::Web, at: "/sidekiq"
  mount Ckeditor::Engine => '/ckeditor'

  controller 'welcome' do
    get 'index'
    get 'news'
    get 'contacts'
    post 'feedback'
    get 'about'
    get 'news/:category_slug/:slug' => 'welcome#show',            as: :post
  end

  root 'welcome#index'



  scope 'lk', module: 'lk' do
    root to: redirect('/login'),   as: :lk
    resources     :users, except: [ :index, :destroy ]
    resources     :user_sessions
    resources     :password_resets
    resources     :payments
    resources     :payouts
    get 'news'                      => 'categories#index',      as: :lk_news
    get 'news/:slug'                => 'categories#show',       as: :lk_category
    get 'news/:category_slug/:slug' => 'posts#show',            as: :lk_post
  end

  namespace 'admin', path: 'adm' do
    root 'users#index'
    resources :users
    resources :questions
    resources :payouts, only: [ :index ]
    post 'payouts/:user_id/pay' => 'payouts#pay', as: :pay
    resources :settings
    resources :mailers
    resources :posts
    resources :categories
  end

  get 'login'     =>  'lk/user_sessions#new',     as: :login
  get 'logout'    =>  'lk/user_sessions#destroy', as: :logout
  get 'profile'   =>  'lk/users#show',            as: :profile
  get 'lk/faq'    => 'application#faq',           as: :faq
  get 'lk/grant'  => 'application#grant',         as: :grant
  post 'lk/grant' => 'application#grant_request', as: :grant_request
end

app/models/setting.rb
# Admin mailers controller
class Setting < RailsSettings::CachedSettings
  scope :mailers, -> {
    where(var: [:reset_password_email, :hello_email, :success_payment, :resembling_email])
  }

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController

  def index
    @settings = Setting.unscoped.where.not(var: [:reset_password_email, :hello_email, :success_payment, :resembling_email])
  end

  def edit
    @setting = Setting.unscoped.find params[:id]
  end

  def update
    setting = Setting.unscoped.find params[:id]
    respond_to do |format|
      Setting[setting.var] = params[:setting][:value]
      format.html { redirect_to admin_settings_path, notice: 'Успешное редактирование' }
    end
  end

end

app/views/admin/settings/edit.html.slim
= simple_form_for [:admin, @setting], html: { class: "form-horizontal" } do |f|
  = f.input :value
  = f.button :submit, :class => 'btn-primary'

app/views/admin/settings/index.html.slim
.row
  .col-sm-12
    table.table
      thead
        tr
          th Название
          th Значение
          th Действия
      tbody
        - @settings.find_each do |setting|
          tr
            td= setting.var
            td= setting.value
            td
              = link_to "<i class='fa fa-pencil'></i>".html_safe, edit_admin_setting_path(setting), class: 'btn btn-default', title: 'редактировать'
              = link_to '<i class="fa fa-trash-o"></i>'.html_safe, admin_setting_path(setting), method: :DELETE, data: { confirm: 'Вы уверенны?' }, class: 'btn btn-danger', title: "Удалить"