config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'bzclass' && password == '12345'
  end
  mount Sidekiq::Web, at: "/sidekiq"
  mount Ckeditor::Engine => '/ckeditor'

  controller 'welcome' do
    get 'index'
    get 'news'
    get 'contacts'
    post 'feedback'
    get 'about'
    get 'news/:category_slug/:slug' => 'welcome#show',            as: :post
  end

  root 'welcome#index'



  scope 'lk', module: 'lk' do
    root to: redirect('/login'),   as: :lk
    resources     :users, except: [ :index, :destroy ]
    resources     :user_sessions
    resources     :password_resets
    resources     :payments
    resources     :payouts
    get 'news'                      => 'categories#index',      as: :lk_news
    get 'news/:slug'                => 'categories#show',       as: :lk_category
    get 'news/:category_slug/:slug' => 'posts#show',            as: :lk_post
  end

  namespace 'admin', path: 'adm' do
    root 'users#index'
    resources :users
    resources :questions
    resources :payouts, only: [ :index ]
    post 'payouts/:user_id/pay' => 'payouts#pay', as: :pay
    resources :settings
    resources :mailers
    resources :posts
    resources :categories
  end

  get 'login'     =>  'lk/user_sessions#new',     as: :login
  get 'logout'    =>  'lk/user_sessions#destroy', as: :logout
  get 'profile'   =>  'lk/users#show',            as: :profile
  get 'lk/faq'    => 'application#faq',           as: :faq
  get 'lk/grant'  => 'application#grant',         as: :grant
  post 'lk/grant' => 'application#grant_request', as: :grant_request
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy, counter_cache: true
  validates :name, presence: true
  # validates :is_public, presence: true
  include Sluggable

  scope :is_public, -> { where(is_public: true) }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  defaults resource_class: Category, collection_name: 'categories', instance_name: 'category'

  def create
    create! do |format|
      format.html { redirect_to admin_posts_path }
    end
  end

  def update
    update! do |format|
      format.html { redirect_to admin_posts_path }
    end
  end

  def destroy
    destroy! do |format|
      format.html { redirect_to admin_posts_path }
    end
  end

  protected

  def collection
    get_collection_ivar ||
      set_collection_ivar(end_of_association_chain.paginate page: params[:page])
  end

  def category_params
    params.require(:category).permit(:id, :name, :is_public)
  end
end

app/controllers/lk/categories_controller.rb
class Lk::CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @category = @categories.first
    @main_post = @category.posts.is_main.first
    @posts = @category.posts.not_main.paginate(page: params[:page], per_page: 3).order(id: :desc)
  end

  def show
    @categories = Category.all
    @category = Category.includes(:posts).find_by_slug(params[:slug])
    @main_post = @category.posts.is_main.first
    @posts = @category.posts.not_main.paginate(page: params[:page], per_page: 3).order(id: :desc)
  end

end

app/views/admin/categories/_form.html.slim
= simple_form_for [ :admin, @category ], :html => { :class => "form-horizontal" } do |f|
  = f.input :name
  = error_span(@category[:name])
  = f.input :is_public
  = error_span(@category[:is_public])
  = f.button :submit,(@category.new_record? ? 'Создать категорию' : 'Сохранить изменения'), :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_categories_path, :class => 'btn btn-default'

app/views/admin/categories/edit.html.slim
- model_class = Category
div class="page-header"
  h1 Изменить категорию
= render :partial => "form"

app/views/admin/categories/index.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:is_public)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @categories.each do |category|
      tr
        td= link_to category.id, admin_category_path(category.id)
        td= category.name
        td= category.is_public
        td=l category.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_category_path(category.id), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_category_path(category.id), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= will_paginate @categories, renderer: BootstrapPagination::Rails

= link_to t('.new', :default => t("helpers.links.new")), new_admin_category_path, :class => 'btn btn-primary'

app/views/admin/categories/new.html.slim
- model_class = Category
div class="page-header"
  h1 Новая категория
= render :partial => "form"

app/views/admin/categories/show.html.slim
- model_class = Category
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @category.name
p
  strong= model_class.human_attribute_name(:slug) + ':'
  br
  = @category.slug
p
  strong= model_class.human_attribute_name(:is_public) + ':'
  br
  = @category.is_public

= link_to t('.back', :default => t("helpers.links.back")), admin_categories_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_category_path(@category.id), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), admin_category_path(@category.id), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'